### ISSUE TITLE
(Bug) Middle Mouse Menu not working after printing ship.

### ISSUE THREAD

**Issue by CaptainLocke** [sstixrud/WeaponCore#195]
## Is this a multiplayer or singleplayer bug?
Both

## Describe the bug:
Printed a ship with a projector. Middle mouse menu pops up, but will not let me access any weapon options.

## Steps To Reproduce:
Print ship with projector. Cut new ship from old grid. Get in cockpit. Press MIddle mouse button. Menu comes up, unable to scroll or select groups.

### User Error Report (if Weapon-Specific) and log files
*WeaponCore lets you generate an error report for a specific weapon, while ingame, hold Ctrl+R and aim the red line at the Weapon that is erroring, and an error report will be generated in WeaponCores log cache: `Users\UserName\AppData\Roaming\SpaceEngineers\Storage\1918681825.sbm_WeaponCore`

Zip up that folder and link it here:
https://drive.google.com/file/d/1632fQzPjWdRaoQHSaWD-Z-8_PDqc0Y4n/view?usp=sharing

**Comment by CaptainLocke** [comment]
Quick update after further testing. 

The menu works as expected before you cut the grid. However, after the ship becomes a new grid by cutting, the menu breaks completely until you reload the save or restart the server.

**Comment by CaptainLocke** [comment]
Another update. Seems to happen when separating a grid from its original grid at the start of the server/game.

If a ship starts connected to another grid, either via an actual connector or a merge block or being physically connected to a grid the Middle Mouse Menu seems to lose track of everything. Upon reconnecting the ship to its original grid the menu works again.

During all of this, the turrets still work and use the settings last set.

**Comment by sstixrud** [comment]
Please retest with the new update I just pushed and let me know.  Also confirm this is repeatable in single player.  If so please include a worldsave and specific instructions on how to reproduce.

**Comment by sstixrud** [comment]
@CaptainLocke

**Comment by CaptainLocke** [comment]
Still happens. Step to reproduce. 

Print ship
Disconnect ship from projector 
Middle mousemenu no longer recognizes turret groups.
Only way to fix this is to restart world/server

**Comment by sstixrud** [comment]
@captainlocke can you provide a world please?

**Comment by CaptainLocke** [comment]
[Weaponcoretest 2.zip](https://github.com/sstixrud/WeaponCore/files/5048688/Weaponcoretest.2.zip)
 Note: The menu will work fine in this world because it's been restarted. To get the bug, you have to make the ship by welding it together and then chopping it from the main grid.

**Comment by sstixrud** [comment]
This issue should be fixed.
